# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0002_auto_20180601_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
