# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 11:09
from __future__ import unicode_literals

from django.db import migrations

import autoslug

from ..models import Article, Category

def migrate_data_forward(apps, schema_editor):
    for instance in Article.objects.all():
        print('Generating slug for %s' % instance)
        instance.save() # Will trigger slug update
    for instance in Category.objects.all():
        print('Generating slug for %s' % instance)
        instance.save() # Will trigger slug update
        

def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    
    dependencies = [
        ('my_newsapp', '0005_auto_20180605_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, default=None, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, default=None, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
        # migrations.RunPython(
        #     migrate_data_forward,
        #     migrate_data_backward,
        # ),
    ]
