# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0009_auto_20180612_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='first_paragraph',
        ),
        migrations.AddField(
            model_name='article',
            name='second_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
