# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0010_auto_20180614_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='first_paragraph',
            new_name='first_part',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='second_paragraph',
            new_name='second_part',
        ),
    ]
