# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0015_auto_20180705_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
