# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0016_auto_20180705_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
