# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0022_auto_20180914_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='icon',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
