# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0023_file_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
