# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0024_auto_20180926_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='icon',
        ),
    ]
