# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_newsapp', '0033_auto_20190227_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='short_description_hr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug_hr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_hr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_hr',
        ),
    ]
