# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
    ]
