# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20190227_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_hr',
            field=models.TextField(null=True),
        ),
    ]
