# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20190227_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text_hr',
        ),
    ]
