---
- name: Django Staging Update
  hosts: production_server

  vars:
    git_url: '{{ lookup("env", "SEMAPHORE_GIT_URL") }}'
    requirements: '{{ lookup("env", "REQUIREMENTS_FILE") }}'
    app_path: '{{ lookup("env", "PROJECT_DIR") }}'
    virtualenv: '{{ lookup("env", "VENV_DIR") }}'
    settings_module: '{{ lookup("env", "SETTINGS_MODULE") }}'
    uwsgi_file: '{{ lookup("env", "UWSGI_INI_FILENAME") }}'

  tasks:
    - name: Update code
      # We have to use command module instead of git:
      #   https://stackoverflow.com/questions/41178361/how-to-use-ansible-git-module-pull-a-branch-with-local-changes
      #   https://discourse.roots.io/t/deployment-failure-due-to-local-modifications-on-production-server/5568
      # git:
      #   repo: "{{ git_url }}"
      #   dest: "{{ app_path }}"
      #   update: yes
      command:
        chdir: "{{ app_path }}"
        cmd: git pull origin master

    - name: Update requirements
      pip:
        virtualenv: "{{ virtualenv }}"
        requirements: "{{ app_path }}/{{ requirements }}"

    - name: Run Migrations
      django_manage:
        command: migrate
        settings: '{{ settings_module }}'
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv }}"

    - name: Collect staticfiles
      django_manage:
        command: collectstatic --link --noinput
        settings: '{{ settings_module }}'
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv }}"

    - name: Makemessages
      django_manage:
        command: makemessages --all
        settings: '{{ settings_module }}'
        app_path: "{{ app_path }}"
        virtualenv: "{{ virtualenv }}"

    - name: Restart app
      file:
        path: /etc/uwsgi-emperor/vassals/{{ uwsgi_file }}
        state: touch
